### ISSUE TITLE
npm package installation fails in ubuntu

### ISSUE THREAD

**Issue by kmanimca2008** [ERS-HCL/nxplorerjs-microservice-starter#174]
* **I'm submitting a ...**
[ * ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**

npm install command fails to install all the dependencies .

2656 silly saveTree +-- swagger-ui-express@4.0.1
2656 silly saveTree `-- yamljs@0.3.0
2657 verbose stack ZlibError: zlib: unexpected end of file
2657 verbose stack     at Zlib.(anonymous function).onerror (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
2657 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
2657 verbose stack     at Unzip.flush (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
2657 verbose stack     at Unzip.end (/usr/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
2657 verbose stack     at Object.end (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
2657 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
2657 verbose stack     at Object.onceWrapper (events.js:313:30)
2657 verbose stack     at emitNone (events.js:111:20)
2657 verbose stack     at PassThrough.emit (events.js:208:7)
2657 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
2657 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
2657 verbose stack     at process._tickCallback (internal/process/next_tick.js:181:9)
2658 verbose cwd /home/manikandan/mani/nxplorerjs-microservice-starter
2659 verbose Linux 4.15.0-38-generic
2660 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2661 verbose node v8.12.0
2662 verbose npm  v6.4.1
2663 error code Z_BUF_ERROR
2664 error errno -5
2665 error zlib: unexpected end of file
2666 verbose exit [ -5, true ]

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

Just clone the repo in ubuntu env and try to install the dep.

* **What is the expected behavior?**

After cloning the repo , npm install should install all the pkgs and it should allow us to run the app.

* **Please tell us about your environment:**

- nxplorer version: 1.5.6
- other environment details
-node -8.12.0
npm -6.4.1
ubuntu 16

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. npm , github, stackoverflow etc)

**Comment by tsukhu** [comment]
This problem is not related to the project as if you see the project builds fine on Travis (Linux)

The issue you are facing is related to npm and npm install is not able to update the package-json.lock file

Possible solutions for you
npm install --no-package-lock
The --no-package-lock argument will prevent npm from creating a package-lock.json file.

or delete the package-lock.json file and then try

**Comment by riginoommen** [comment]
I am aslo facing this same issue

**Comment by riginoommen** [comment]
```
riginoommen-mac:nxplorerjs-microservice-starter riginoommen$ npm i
npm ERR! Unexpected end of JSON input while parsing near '...(https://github.com/G'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riginoommen/.npm/_logs/2019-12-17T06_58_00_113Z-debug.log
riginoommen-mac:nxplorerjs-microservice-starter riginoommen$ 
```

**Comment by tsukhu** [comment]
Thank you for posting this. I've been using Windows and travis seems to work. Will investigate

**Comment by tsukhu** [comment]
Can you'll update the version of node js to the latest instead of 6 and see it works. I'll get hold of a ubuntu machine to test as well . https://stackoverflow.com/questions/48739985/npm-err-code-z-buf-error-when-install

**Comment by tsukhu** [comment]
Also see this one https://stackoverflow.com/questions/47675478/npm-install-errorunexpected-end-of-json-input-while-parsing-near-nt-webpack
